### PR TITLE
docs: Code to demonstrate the dialect usage

### PR DESCRIPTION
**Pull request by amanPras**
Code to demonstrate the dialect usage. This is just for documentation purpose.

### CODE REVIEW

**Comment by ishche** [comment]
Does it make sense to have the same name of the dialect in server and client parts?
`my-rule-dialect-support` is a bit confusing.

**Comment by amanPras** [comment]
> Does it make sense to have the same name of the dialect in server and client parts? `my-rule-dialect-support` is a bit confusing.

👍 Yes. I will update

**Comment by ishche** [comment]
I think it's okay to merge a sample dialect for educational purposes into the main branch. Is it ready to be merged?

**Comment by amanPras** [comment]
> I think it's okay to merge a sample dialect for educational purposes into the main branch. Is it ready to be merged?

I will resolve the merge conflicts

**Review by ishche — APPROVED** [review]

**Comment by amanPras** [comment]
closing as this need to be moved a template repo

**Pull request closed without merging**
