### PR TITLE
feat: Add support for Binary Host Variable Arrays

### PR DESCRIPTION
**Pull request by mm-broadcom**
## How Has This Been Tested?

Wrote and compiled a small COBOL program with various setups for the binary host variable array.

```
       Identification Division.
        Program-Id. 'TEST1'.
        Data Division.
         Working-Storage Section.
         01 VAR-BIN.
         02 VAR-BIN-ARR SQL TYPE IS BINARY(255) OCCURS 32767 TIMES.
         02 VAR-BIN-ARR-NT SQL TYPE IS BINARY(255) OCCURS 32767.

         02 VAR-VBIN-ARR SQL TYPE IS VARBINARY(32704) OCCURS 1 TIMES.
         02 VAR-VBIN-ARR-NT SQL TYPE IS VARBINARY(32704) OCCURS 1.

         02 VAR-INVALID-BIN-ARR SQL TYPE IS BINARY(256) OCCURS -1 TIMES.
         02 VAR-INVALID-VBIN-ARR SQL TYPE IS VARBINARY(32705) OCCURS -1234.
        PROCEDURE division.
```
NOTE: The last two variables are invalid on purpose to test the semantic checks on length.

## Checklist:
- [x] Each of my commits contains one meaningful change
- [x] I have performed rebase of my branch on top of the development
- [x] I have performed a self-review of my own code
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] I have checked my code and corrected any misspellings

### CODE REVIEW

**Comment by amanPras** [comment]
changes LGTM. I am wondering if we need to add the newly added lexemes to the coloring and auto completion. Can @mm-broadcom please verify it?
Also, please rebase with development  ( I see `This branch cannot be rebased due to conflicts` )

**Comment by mm-broadcom** [comment]
@ap891843 Went ahead and rebased the PR. Also checked and the new to grammar terms are already in the `COBOL.tmlanguage.json` and the `LanguageKeywords.txt` files. (That handles highlighting and auto-completion respectively.)

**Comment by amanPras** [comment]
> @ap891843 Went ahead and rebased the PR. Also checked and the new to grammar terms are already in the `COBOL.tmlanguage.json` and the `LanguageKeywords.txt` files. (That handles highlighting and auto-completion respectively.)

For the SQL coloring, [SQL syntax file](https://github.com/eclipse-che4z/che-che4z-lsp-for-cobol/blob/development/clients/cobol-lsp-vscode-extension/syntaxes/SQL.tmLanguage.json) is used

**Comment by amanPras** [comment]
> @ap891843 Went ahead and rebased the PR. Also checked and the new to grammar terms are already in the `COBOL.tmlanguage.json` and the `LanguageKeywords.txt` files. (That handles highlighting and auto-completion respectively.)

Also, just fyi, we wanted to use a different [file](https://github.com/eclipse-che4z/che-che4z-lsp-for-cobol/blob/development/server/engine/src/main/resources/LanguageKeywords_sql.txt)for sql auto completion. But we never managed to clean it up. So, it should be fine :)

**Review by amanPras — APPROVED** [review]

**Comment by amanPras** [comment]
#2320

**Pull request merged**
