### PR TITLE
Chore/dependency audit

### PR DESCRIPTION
**Pull request by amanPras**
## How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [ ] No change in the functionality. Check for no regression.

## Checklist:
- [x] Each of my commits contains one meaningful change
- [x] I have performed rebase of my branch on top of the development
- [x] I have performed a self-review of my own code
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] I have checked my code and corrected any misspellings

### CODE REVIEW

**Comment by amanPras** [comment]
https://github.com/eclipse-che4z/che-che4z-lsp-for-cobol/pull/1983/commits/fe488128e97561249d99a3f68b28e9c714035118 removes the cypress-related code which we don't use now. 
@ishche @Nurkambay @SWETAS04  @ilidio-lopes Is it ok to delete these or do we plan to keep them until we migrate to vscode tests?

**Review by ishche — APPROVED** [review]
I would say REMOVE IT!

**Comment by ilidio-lopes** [comment]
I would remove it but I'd like to know what the PO thinks

**Comment by ishche** [comment]
We will bring cypress tests back if we will miss it :)

**Comment by zimlu02** [comment]
remove it if we don't use it.

**Pull request merged**
