### PR TITLE
Fix downloaded copybooks are not getting resolved

### PR DESCRIPTION
**Pull request by KutluOzel-b**
## How Has This Been Tested?

Open a cobol program that uses copybooks 
configure copybook download paths or use endevor integration
check downloaded copybooks are getting resolved.

## Checklist:
- [x] Each of my commits contains one meaningful change
- [x] I have performed rebase of my branch on top of the development
- [x] I have performed a self-review of my own code
- [] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] I have checked my code and corrected any misspellings

### CODE REVIEW

**Review by slavek-kucera — CHANGES_REQUESTED** [review]
I suggest closing this one in favor of #2432.

**Comment by KutluOzel-b** [comment]
> I suggest closing this one in favor of #2432.


This pr is the one that solves the problem. https://github.com/eclipse-che4z/che-che4z-lsp-for-cobol/pull/2432 is the draft pr that has been raised to just to show making requests in queue doesn't solve the problem but cancelling "discard anaylsis" does.

**Comment by slavek-kucera** [comment]
Could you elaborate on how waiting 100ms at the end of a process the language server does not wait for and then starting a directory enumeration and not waiting the the result of the operation "solves the problem"?

**Comment by KutluOzel-b** [comment]
> Could you elaborate on how waiting 100ms at the end of a process the language server does not wait for and then starting a directory enumeration and not waiting the the result of the operation "solves the problem"?

After checking that this doesn't trigger **filewatcher** event, closing the pr since doesn't solve the issue

**Pull request closed without merging**
