### PR TITLE
fix: expose analysis API

### PR DESCRIPTION
**Pull request by amanPras**
## How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [x] Test A - check that CCF plugin works with this

## Checklist:
- [x] Each of my commits contains one meaningful change
- [x] I have performed rebase of my branch on top of the development
- [x] I have performed a self-review of my own code
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] I have checked my code and corrected any misspellings

### CODE REVIEW

**Comment by VitGottwald** [comment]
What is this needed for?

**Comment by amanPras** [comment]
> What is this needed for?

This exposes api for CCF graph

**Comment by VitGottwald** [comment]
What about having a test to show it on a simple program?

**Comment by amanPras** [comment]
> What about having a test to show it on a simple program?

Added a test

**Review by VitGottwald — APPROVED** [review]

**Review by ishche — APPROVED** [review]

**Pull request merged**
