### PR TITLE
table locators

### PR DESCRIPTION
**Pull request by ilidio-lopes**
## How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [x] tested on VSC
image

- [x] tested by running the unit test

- [ ] Test A
- [ ] Test B

## Checklist:
- [x] Each of my commits contains one meaningful change
- [x] I have performed rebase of my branch on top of the development
- [x] I have performed a self-review of my own code
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] I have checked my code and corrected any misspellings

### CODE REVIEW

**Comment by amanPras** [comment]
LGTM! except for the discussed/known following issue

`1 level-1 indicates a COBOL level in the range 2–48.`

because of which below compliable code gives diagnostics
```cobol
        Identification Division.
        Program-Id. 'TEST1'.
        Data Division.
        Working-Storage Section.
        01 TEST-1.
          05 VAR-NAME1 USAGE IS SQL TYPE IS TABLE LIKE TABLENAME
        AS LOCATOR.
        PROCEDURE division.
           display  VAR-NAME1.

```

**Comment by amanPras** [comment]
Below code fails to compile with sql co processor 
coz, it tries to append this 02 level to the implicit sql variable
```

      0   1  SQL-FILE-APPEND . . . . . . . . . . . . . . .             000000000   DS 0CL4           Group          G
      5     2  VAR-NAME1 . . . . . . . . . . . . . . . . .             000000000   DS 4C             Binary         G
```

resulting in below error

```
 ==000005==> IGYDS1052-E Group item "SQL-FILE-APPEND" contained the "PICTURE" clause.  The clause
                         was discarded.

 ==000005==> IGYDS1277-E A "VALUE" clause was specified for a group item that contained a
                         subordinate item with "USAGE" other than "USAGE DISPLAY". The "VALUE"
                         clause was discarded.
```



```cobol
        Identification Division.
        Program-Id. 'TEST1'.
        Data Division.
        Working-Storage Section.
        02 VAR-NAME1 USAGE IS SQL TYPE IS TABLE LIKE TABLENAME
        AS LOCATOR.
        PROCEDURE division.
           display  VAR-NAME1.

```

**Comment by amanPras** [comment]
@ilidio-lopes Can we close this PR in favor of https://github.com/eclipse-che4z/che-che4z-lsp-for-cobol/pull/2380
#2380  is based out of commit from this PR

**Comment by ilidio-lopes** [comment]
> @ilidio-lopes Can we close this PR in favor of #2380 #2380 is based out of commit from this PR

yes

**Comment by amanPras** [comment]
closing this in favor of #2380

**Pull request closed without merging**
