### PR TITLE
Add support for DB2 SQL standard language option STDSQL

### PR DESCRIPTION
**Pull request by ilidio-lopes**
## How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [ ] Test A
- [ ] Test B

## Checklist:
- [x] Each of my commits contains one meaningful change
- [x] I have performed rebase of my branch on top of the development
- [x] I have performed a self-review of my own code
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [ ] I have checked my code and corrected any misspellings

### CODE REVIEW

**Comment by ilidio-lopes** [comment]
#973

**Comment by amanPras** [comment]
is STDSQL(YES) a compiler option ?
If yes, we could use the CompilerDirectivesStage to populate the proper directive and that could be used in db2 dialect.

**Comment by ilidio-lopes** [comment]
> is STDSQL(YES) a compiler option ? If yes, we could use the CompilerDirectivesStage to populate the proper directive and that could be used in db2 dialect.

Its a precompiler option
https://www.ibm.com/docs/en/db2-for-zos/13?topic=messages-dsnh081i

**Comment by amanPras** [comment]
> > is STDSQL(YES) a compiler option ? If yes, we could use the CompilerDirectivesStage to populate the proper directive and that could be used in db2 dialect.
> 
> Its a precompiler option https://www.ibm.com/docs/en/db2-for-zos/13?topic=messages-dsnh081i

Looks like a compiler directive. I believe we should use compiler directive infra rather than changing AnalysisConfig class.
We can refer to https://github.com/eclipse-che4z/che-che4z-lsp-for-cobol/blob/4a8572cd1a9fb0018fd4083f31336d1d2854de26/server/engine/src/main/java/org/eclipse/lsp/cobol/implicitDialects/cics/CICSDialect.java#L104
May be we would want to introduce this directive as a configuration in processor group that would mean changes to https://github.com/eclipse-che4z/che-che4z-lsp-for-cobol/blob/4a8572cd1a9fb0018fd4083f31336d1d2854de26/server/common/src/main/java/org/eclipse/lsp/cobol/common/processor/CompilerDirectiveName.java#L27 and
 https://github.com/eclipse-che4z/che-che4z-lsp-for-cobol/blob/development/clients/cobol-lsp-vscode-extension/schema/compiler_options.schema.json

Now I am not sure if these changes should be done in this PR or should be taken as a refactoring task.

**Pull request closed without merging**
